services:
  - type: web
    name: mfm-ncr12-reports
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_BUCKET
        sync: false
